# Generated by Django 3.2.6 on 2021-09-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='ratings',
            field=models.FloatField(),
        ),
    ]
