# Generated by Django 3.2.9 on 2022-01-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exams',
            name='name',
            field=models.CharField(blank=True, choices=[('ias', 'ias'), ('iasHindi', 'iasHindi'), ('jee', 'jee'), ('jeeMains', 'jeeMains'), ('jeeAdv', 'jeeAdv'), ('neet', 'neet'), ('ras', 'ras'), ('rasHindi', 'rasHindi'), ('ibpsPO', 'ibpsPO'), ('ibpsClerk', 'ibpsClerk'), ('sscCHSL', 'sscCHSL'), ('sscCGL', 'sscCGL'), ('sscCGLHindi', 'sscCGLHindi'), ('nda', 'nda'), ('cds', 'cds'), ('ntpc', 'ntpc'), ('reet1', 'reet1'), ('reet2', 'reet2'), ('reet2Science', 'reet2Science'), ('patwari', 'patwari'), ('grade2nd', 'grade2nd'), ('grade2ndHindi', 'grade2ndHindi'), ('grade2ndScience', 'grade2ndScience'), ('grade2ndSS', 'grade2ndSS'), ('sscGD', 'sscGD'), ('sscMTS', 'sscMTS'), ('rajPoliceConst', 'rajPoliceConst'), ('rajLDC', 'rajLDC'), ('rrbGD', 'rrbGD'), ('sipaper1', 'sipaper1'), ('sipaper2', 'sipaper2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='explaination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(choices=[('physicsAdv', 'physicsAdv'), ('mathsAdv', 'mathsAdv'), ('chemAdv', 'chemAdv'), ('physicsMains', 'physicsMains'), ('mathsMains', 'mathsMains'), ('chemMains', 'chemMains'), ('physicsNeet', 'physicsNeet'), ('chemNeet', 'chemNeet'), ('bio', 'bio'), ('reasoningHard', 'reasoningHard'), ('reasoningEasy', 'reasoningEasy'), ('currentAffairsWorldEasy', 'currentAffairsWorldEasy'), ('currentAffairsWorldHard', 'currentAffairsWorldHard'), ('currentAffairsIndiaEasy', 'currentAffairsIndiaEasy'), ('currentAffairsIndiaHard', 'currentAffairsIndiaHard'), ('quantAptHard', 'quantAptHard'), ('quantAptEasy', 'quantAptEasy'), ('englishLangAndComprehensionEasy', 'englishLangAndComprehensionEasy'), ('englishLangAndComprehensionHard', 'englishLangAndComprehensionHard'), ('basicComputer', 'basicComputer'), ('economyAndBanking', 'economyAndBanking'), ('geographyIndHard', 'geographyIndHard'), ('geographyIndEasy', 'geographyIndEasy'), ('geographyWorld', 'geographyWorld'), ('polityIndEasy', 'polityIndEasy'), ('polityIndHard', 'polityIndHard'), ('economyIndGen', 'economyIndGen'), ('economyIndBudgetAndSchemes', 'economyIndBudgetAndSchemes'), ('environmentAndEcologyEasy', 'environmentAndEcologyEasy'), ('environmentAndEcologyHard', 'environmentAndEcologyHard'), ('historyIndEasy', 'historyIndEasy'), ('historyIndHard', 'historyIndHard'), ('historyWorld', 'historyWorld'), ('InternationalRelationAndSecurity', 'InternationalRelationAndSecurity'), ('sciAndTechEasy', 'sciAndTechEasy'), ('sciAndTechHard', 'sciAndTechHard'), ('generalScience', 'generalScience'), ('geographyRajEasy', 'geographyRajEasy'), ('geographyRajHard', 'geographyRajHard'), ('historyRajEasy', 'historyRajEasy'), ('historyRajHard', 'historyRajHard'), ('artAndCultureRaj', 'artAndCultureRaj'), ('polityRajHard', 'polityRajHard'), ('polityRajEasy', 'polityRajEasy'), ('currentAffairsRajHard', 'currentAffairsRajHard'), ('currentAffairsRajEasy', 'currentAffairsRajEasy'), ('artAndCultureInd', 'artAndCultureInd'), ('economyRajHard', 'economyRajHard'), ('economyRajEasy', 'economyRajEasy'), ('constitutionAndGovernance', 'constitutionAndGovernance'), ('decisionMaking', 'decisionMaking'), ('ndaHistory', 'ndaHistory'), ('ndaMaths', 'ndaMaths'), ('cdsMaths', 'cdsMaths'), ('currentEvents', 'currentEvents'), ('dataAnalysisAndInterpretation', 'dataAnalysisAndInterpretation'), ('financialAwareness', 'financialAwareness'), ('financeAndAccounts', 'financeAndAccounts'), ('statistics', 'statistics'), ('childDevelopmentAndEdu', 'childDevelopmentAndEdu'), ('teachingApt', 'teachingApt'), ('hindi', 'hindi'), ('staticGK', 'staticGK'), ('rpcGKInd', 'rpcGKInd'), ('rpcGKRaj', 'rpcGKRaj'), ('rpcReasoning', 'rpcReasoning'), ('gdQuantApt', 'gdQuantApt'), ('iasMisc', 'iasMisc'), ('jeeMisc', 'jeeMisc'), ('jeeMainsMisc', 'jeeMainsMisc'), ('jeeAdvMisc', 'jeeAdvMisc'), ('neetMisc', 'neetMisc'), ('rasMisc', 'rasMisc'), ('ibpsPOMisc', 'ibpsPOMisc'), ('ibpsClerkMisc', 'ibpsClerkMisc'), ('sscCHSLMisc', 'sscCHSLMisc'), ('sscCGLMisc', 'sscCGLMisc'), ('ndaMisc', 'ndaMisc'), ('cdsMisc', 'cdsMisc'), ('ntpcMisc', 'ntpcMisc'), ('reet1Misc', 'reet1Misc'), ('reet2Misc', 'reet2Misc'), ('patwariMisc', 'patwariMisc'), ('grade2ndMisc', 'grade2ndMisc'), ('grade2ndScienceMisc', 'grade2ndScienceMisc'), ('grade2ndSSMisc', 'grade2ndSSMisc'), ('sscGDMisc', 'sscGDMisc'), ('sscMTSMisc', 'sscMTSMisc'), ('rajPoliceConstMisc', 'rajPoliceConstMisc'), ('rajLDCMisc', 'rajLDCMisc'), ('rrbGDMisc', 'rrbGDMisc'), ('sipaper1Misc', 'sipaper1Misc'), ('sipaper2Misc', 'sipaper2Misc'), ('reet2ScienceMisc', 'reet2ScienceMisc'), ('iasMiscHindi', 'iasMiscHindi'), ('rasMiscHindi', 'rasMiscHindi'), ('sscCGLMiscHindi', 'sscCGLMiscHindi')], default='mathsAdv', max_length=100000),
        ),
    ]
