# Generated by Django 3.2.6 on 2021-09-02 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0002_alter_questions_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='ratedBy',
            field=models.ManyToManyField(related_name='ratedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='seenBy',
            field=models.ManyToManyField(related_name='seenBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
