# Generated by Django 3.2.6 on 2021-09-02 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0003_auto_20210902_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='ratedBy',
            field=models.ManyToManyField(blank=True, related_name='ratedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='seenBy',
            field=models.ManyToManyField(blank=True, related_name='seenBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
