# Generated by Django 3.2.9 on 2021-12-29 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0003_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionQuestion', to='Questions.questions')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='submissionSelectedOptions', to='Questions.Options')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissionUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='exams',
            name='name',
            field=models.CharField(blank=True, choices=[('ias', 'ias'), ('jee', 'jee'), ('jeeMains', 'jeeMains'), ('jeeAdv', 'jeeAdv'), ('neet', 'neet'), ('ras', 'ras'), ('ibpsPO', 'ibpsPO'), ('ibpsClerk', 'ibpsClerk'), ('sscCHSL', 'sscCHSL'), ('sscCGL', 'sscCGL'), ('nda', 'nda'), ('cds', 'cds'), ('cat', 'cat'), ('ntpc', 'ntpc'), ('cdsEnglish', 'cdsEnglish'), ('cdsGk', 'cdsGk'), ('cdsMaths', 'cdsMaths')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='WeeklyCompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_options', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeklyCompetitions', to='Questions.weeklycompetitions')),
                ('submissions', models.ManyToManyField(blank=True, related_name='weeklyCompetitionSubmissions', to='Questions.Submissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
