# Generated by Django 3.2.9 on 2022-01-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_auto_20220103_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='name',
            field=models.CharField(blank=True, choices=[('ias', 'ias'), ('iasHindi', 'iasHindi'), ('jee', 'jee'), ('jeeMains', 'jeeMains'), ('jeeAdv', 'jeeAdv'), ('neet', 'neet'), ('ras', 'ras'), ('rasHindi', 'rasHindi'), ('ibpsPO', 'ibpsPO'), ('ibpsClerk', 'ibpsClerk'), ('sscCHSL', 'sscCHSL'), ('sscCGL', 'sscCGL'), ('sscCGLHindi', 'sscCGLHindi'), ('nda', 'nda'), ('cds', 'cds'), ('ntpc', 'ntpc'), ('reet1', 'reet1'), ('reet2', 'reet2'), ('reet2Science', 'reet2Science'), ('patwari', 'patwari'), ('grade2nd', 'grade2nd'), ('grade2ndScience', 'grade2ndScience'), ('grade2ndSS', 'grade2ndSS'), ('sscGD', 'sscGD'), ('sscMTS', 'sscMTS'), ('rajPoliceConst', 'rajPoliceConst'), ('rajLDC', 'rajLDC'), ('rrbGD', 'rrbGD'), ('sipaper1', 'sipaper1'), ('sipaper2', 'sipaper2')], max_length=20, null=True),
        ),
    ]
