# Generated by Django 3.2.9 on 2022-01-01 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_load_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsofthedays',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questionsofthedays',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quesOfDayExam', to='Questions.exams'),
        ),
        migrations.AlterField(
            model_name='questionsofthedays',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionsOfTheDays', to='Questions.questions'),
        ),
        migrations.AlterField(
            model_name='questionsofthedays',
            name='uuid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
