# Generated by Django 3.2.6 on 2021-09-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_auto_20210902_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='time',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
