# Generated by Django 3.2.6 on 2021-09-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_alter_questions_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='time',
        ),
        migrations.AddField(
            model_name='questions',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
