# Generated by Django 3.2.6 on 2021-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0007_auto_20210902_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='options',
        ),
        migrations.AddField(
            model_name='questions',
            name='options',
            field=models.ManyToManyField(blank=True, to='Questions.Options'),
        ),
    ]
