# Generated by Django 3.2.6 on 2021-09-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0008_auto_20210902_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
