# Generated by Django 3.2.6 on 2021-09-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0010_questions_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='percentCorrect',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ratingsDifficulty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InternationalRelationAndSecurity', models.ManyToManyField(blank=True, related_name='InternationalRelationAndSecurity', to='Questions.Questions')),
                ('basicComputer', models.ManyToManyField(blank=True, related_name='basicComputer', to='Questions.Questions')),
                ('bio', models.ManyToManyField(blank=True, related_name='bio', to='Questions.Questions')),
                ('chemAdv', models.ManyToManyField(blank=True, related_name='chemAdv', to='Questions.Questions')),
                ('chemMains', models.ManyToManyField(blank=True, related_name='chemMains', to='Questions.Questions')),
                ('currentAffairsEasy', models.ManyToManyField(blank=True, related_name='currentAffairsEasy', to='Questions.Questions')),
                ('currentAffairsHard', models.ManyToManyField(blank=True, related_name='currentAffairsHard', to='Questions.Questions')),
                ('economyAndBanking', models.ManyToManyField(blank=True, related_name='economyAndBanking', to='Questions.Questions')),
                ('economyIndBudgetAndSchemes', models.ManyToManyField(blank=True, related_name='economyIndBudgetAndSchemes', to='Questions.Questions')),
                ('economyIndGen', models.ManyToManyField(blank=True, related_name='economyIndGen', to='Questions.Questions')),
                ('englishLangAndComprehension', models.ManyToManyField(blank=True, related_name='englishLangAndComprehension', to='Questions.Questions')),
                ('environmentAndEcology', models.ManyToManyField(blank=True, related_name='environmentAndEcology', to='Questions.Questions')),
                ('generalScience', models.ManyToManyField(blank=True, related_name='generalScience', to='Questions.Questions')),
                ('geographyInd', models.ManyToManyField(blank=True, related_name='geographyInd', to='Questions.Questions')),
                ('geographyWorld', models.ManyToManyField(blank=True, related_name='geographyWorld', to='Questions.Questions')),
                ('historyInd', models.ManyToManyField(blank=True, related_name='historyInd', to='Questions.Questions')),
                ('historyWorld', models.ManyToManyField(blank=True, related_name='historyWorld', to='Questions.Questions')),
                ('mathsAdv', models.ManyToManyField(blank=True, related_name='mathsAdv', to='Questions.Questions')),
                ('mathsGen', models.ManyToManyField(blank=True, related_name='mathsGen', to='Questions.Questions')),
                ('mathsMains', models.ManyToManyField(blank=True, related_name='mathsMains', to='Questions.Questions')),
                ('physicsAdv', models.ManyToManyField(blank=True, related_name='physicsAdv', to='Questions.Questions')),
                ('physicsMains', models.ManyToManyField(blank=True, related_name='physicsMains', to='Questions.Questions')),
                ('polityInd', models.ManyToManyField(blank=True, related_name='polityInd', to='Questions.Questions')),
                ('quantApt', models.ManyToManyField(blank=True, related_name='quantApt', to='Questions.Questions')),
                ('reasoningEasy', models.ManyToManyField(blank=True, related_name='reasoningEasy', to='Questions.Questions')),
                ('reasoningHard', models.ManyToManyField(blank=True, related_name='reasoningHard', to='Questions.Questions')),
                ('sciAndTech', models.ManyToManyField(blank=True, related_name='sciAndTech', to='Questions.Questions')),
            ],
        ),
    ]
