# Generated by Django 3.2.6 on 2021-09-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0011_auto_20210905_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='InternationalRelationAndSecurity',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='basicComputer',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='chemAdv',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='chemMains',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='currentAffairsEasy',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='currentAffairsHard',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='economyAndBanking',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='economyIndBudgetAndSchemes',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='economyIndGen',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='englishLangAndComprehension',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='environmentAndEcology',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='generalScience',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='geographyInd',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='geographyWorld',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='historyInd',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='historyWorld',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='mathsAdv',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='mathsGen',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='mathsMains',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='physicsAdv',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='physicsMains',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='polityInd',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='quantApt',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='reasoningEasy',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='reasoningHard',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='sciAndTech',
        ),
        migrations.AddField(
            model_name='questions',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='Questions.subjects'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
