# Generated by Django 3.2.6 on 2021-09-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0012_auto_20210905_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(choices=[('physicsAdv', 'physicsAdv'), ('mathsAdv', 'mathsAdv'), ('chemAdv', 'chemAdv'), ('physicsMains', 'physicsMains'), ('mathsMains', 'mathsMains'), ('chemMains', 'chemMains'), ('bio', 'bio'), ('reasoningHard', 'reasoningHard'), ('reasoningEasy', 'reasoningEasy'), ('currentAffairsHard', 'currentAffairsHard'), ('currentAffairsEasy', 'currentAffairsEasy'), ('quantApt', 'quantApt'), ('englishLangAndComprehension', 'englishLangAndComprehension'), ('basicComputer', 'basicComputer'), ('mathsGen', 'mathsGen'), ('economyAndBanking', 'economyAndBanking'), ('geographyInd', 'geographyInd'), ('geographyWorld', 'geographyWorld'), ('polityInd', 'polityInd'), ('economyIndGen', 'economyIndGen'), ('economyIndBudgetAndSchemes', 'economyIndBudgetAndSchemes'), ('environmentAndEcology', 'environmentAndEcology'), ('historyInd', 'historyInd'), ('historyWorld', 'historyWorld'), ('InternationalRelationAndSecurity', 'InternationalRelationAndSecurity'), ('sciAndTech', 'sciAndTech'), ('generalScience', 'generalScience')], default='mathsAdv', max_length=100000),
        ),
    ]
