# Generated by Django 3.2.6 on 2021-09-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0013_alter_subjects_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
