# Generated by Django 3.2.6 on 2021-09-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0014_auto_20210913_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='uuid',
        ),
        migrations.AddField(
            model_name='questions',
            name='isExpert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(choices=[('physicsAdv', 'physicsAdv'), ('mathsAdv', 'mathsAdv'), ('chemAdv', 'chemAdv'), ('physicsMains', 'physicsMains'), ('mathsMains', 'mathsMains'), ('chemMains', 'chemMains'), ('bio', 'bio'), ('reasoningHard', 'reasoningHard'), ('reasoningEasy', 'reasoningEasy'), ('currentAffairsWorld', 'currentAffairsWorld'), ('currentAffairsIndiaEasy', 'currentAffairsIndiaEasy'), ('currentAffairsIndiaHard', 'currentAffairsIndiaHard'), ('quantApt', 'quantApt'), ('englishLangAndComprehension', 'englishLangAndComprehension'), ('basicComputer', 'basicComputer'), ('mathsGen', 'mathsGen'), ('economyAndBanking', 'economyAndBanking'), ('geographyInd', 'geographyInd'), ('geographyWorld', 'geographyWorld'), ('polityInd', 'polityInd'), ('economyIndGen', 'economyIndGen'), ('economyIndBudgetAndSchemes', 'economyIndBudgetAndSchemes'), ('environmentAndEcology', 'environmentAndEcology'), ('historyInd', 'historyInd'), ('historyWorld', 'historyWorld'), ('InternationalRelationAndSecurity', 'InternationalRelationAndSecurity'), ('sciAndTech', 'sciAndTech'), ('generalScience', 'generalScience'), ('geographyRaj', 'geographyRaj'), ('historyRaj', 'historyRaj'), ('artAndCultureRaj', 'artAndCultureRaj'), ('polityRaj', 'polityRaj'), ('currentAffairsRajHard', 'currentAffairsRajHard'), ('currentAffairsRajEasy', 'currentAffairsRajEasy')], default='mathsAdv', max_length=100000),
        ),
        migrations.CreateModel(
            name='SeenQuestionsOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Questions.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ManyToManyField(blank=True, related_name='cat', to='Questions.Subjects')),
                ('cds', models.ManyToManyField(blank=True, related_name='cds', to='Questions.Subjects')),
                ('ias', models.ManyToManyField(blank=True, related_name='iasQues', to='Questions.Subjects')),
                ('ibpsClerk', models.ManyToManyField(blank=True, related_name='ibpsClerk', to='Questions.Subjects')),
                ('ibpsPO', models.ManyToManyField(blank=True, related_name='ibpsPO', to='Questions.Subjects')),
                ('jeeAdv', models.ManyToManyField(blank=True, related_name='jeeAdv', to='Questions.Subjects')),
                ('jeeMains', models.ManyToManyField(blank=True, related_name='jeeMains', to='Questions.Subjects')),
                ('nda', models.ManyToManyField(blank=True, related_name='nda', to='Questions.Subjects')),
                ('neet', models.ManyToManyField(blank=True, related_name='neet', to='Questions.Subjects')),
                ('ntpc', models.ManyToManyField(blank=True, related_name='ntpc', to='Questions.Subjects')),
                ('ras', models.ManyToManyField(blank=True, related_name='ras', to='Questions.Subjects')),
                ('sscCGL', models.ManyToManyField(blank=True, related_name='sscCGL', to='Questions.Subjects')),
                ('sscCHSL', models.ManyToManyField(blank=True, related_name='sscCHSL', to='Questions.Subjects')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='exam',
            field=models.ManyToManyField(blank=True, related_name='exams', to='Questions.Exams'),
        ),
    ]
