# Generated by Django 3.2.6 on 2021-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0015_auto_20210915_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='cds',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='ias',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='ibpsClerk',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='ibpsPO',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='jeeAdv',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='jeeMains',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='nda',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='neet',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='ntpc',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='ras',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='sscCGL',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='sscCHSL',
        ),
        migrations.AddField(
            model_name='exams',
            name='name',
            field=models.CharField(blank=True, choices=[('ias', 'ias'), ('jeeMains', 'jeeMains'), ('jeeAdv', 'jeeAdv'), ('neet', 'neet'), ('ras', 'ras'), ('ibpsPO', 'ibpsPO'), ('ibpsClerk', 'ibpsClerk'), ('sscCHSL', 'sscCHSL'), ('nda', 'nda'), ('cds', 'cds'), ('cat', 'cat'), ('ntpc', 'ntpc')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exams',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='Questions.Subjects'),
        ),
    ]
