# Generated by Django 3.2.6 on 2021-09-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0016_auto_20210915_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevQuesOfDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsOfTheDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='ratingsDifficulty',
        ),
        migrations.AddField(
            model_name='questions',
            name='difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SeenQuestionsOfTheDay',
        ),
        migrations.AddField(
            model_name='questionsofthedays',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='Questions.Questions'),
        ),
        migrations.AddField(
            model_name='prevquesofdays',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questions.questions'),
        ),
    ]
