# Generated by Django 3.2.6 on 2021-09-18 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0019_alter_subjects_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='name',
            field=models.CharField(blank=True, choices=[('ias', 'ias'), ('jeeMains', 'jeeMains'), ('jeeAdv', 'jeeAdv'), ('neet', 'neet'), ('ras', 'ras'), ('ibpsPO', 'ibpsPO'), ('ibpsClerk', 'ibpsClerk'), ('sscCHSL', 'sscCHSL'), ('sscCGL', 'sscCGL'), ('nda', 'nda'), ('cds', 'cds'), ('cat', 'cat'), ('ntpc', 'ntpc')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(choices=[('physicsAdv', 'physicsAdv'), ('mathsAdv', 'mathsAdv'), ('chemAdv', 'chemAdv'), ('physicsMains', 'physicsMains'), ('mathsMains', 'mathsMains'), ('chemMains', 'chemMains'), ('bio', 'bio'), ('reasoningHard', 'reasoningHard'), ('reasoningEasy', 'reasoningEasy'), ('currentAffairsWorld', 'currentAffairsWorld'), ('currentAffairsIndiaEasy', 'currentAffairsIndiaEasy'), ('currentAffairsIndiaHard', 'currentAffairsIndiaHard'), ('quantAptHard', 'quantAptHard'), ('quantAptEasy', 'quantAptEasy'), ('englishLangAndComprehension', 'englishLangAndComprehension'), ('basicComputer', 'basicComputer'), ('economyAndBanking', 'economyAndBanking'), ('geographyIndHard', 'geographyIndHard'), ('geographyIndEasy', 'geographyIndEasy'), ('geographyWorld', 'geographyWorld'), ('polityIndEasy', 'polityIndEasy'), ('polityIndHard', 'polityIndHard'), ('economyIndGen', 'economyIndGen'), ('economyIndBudgetAndSchemes', 'economyIndBudgetAndSchemes'), ('environmentAndEcologyEasy', 'environmentAndEcologyEasy'), ('environmentAndEcologyHard', 'environmentAndEcologyHard'), ('historyIndEasy', 'historyIndEasy'), ('historyIndHard', 'historyIndHard'), ('historyWorld', 'historyWorld'), ('InternationalRelationAndSecurity', 'InternationalRelationAndSecurity'), ('sciAndTechEasy', 'sciAndTechEasy'), ('sciAndTechHard', 'sciAndTechHard'), ('generalScience', 'generalScience'), ('geographyRajEasy', 'geographyRajEasy'), ('geographyRajHard', 'geographyRajHard'), ('historyRajEasy', 'historyRajEasy'), ('historyRajHard', 'historyRajHard'), ('artAndCultureRaj', 'artAndCultureRaj'), ('polityRajHard', 'polityRajHard'), ('polityRajEasy', 'polityRajEasy'), ('currentAffairsRajHard', 'currentAffairsRajHard'), ('currentAffairsRajEasy', 'currentAffairsRajEasy'), ('artAndCultureInd', 'artAndCultureInd'), ('economyRajHard', 'economyRajHard'), ('economyRajEasy', 'economyRajEasy'), ('constitutionAndGovernance', 'constitutionAndGovernance'), ('decisionMaking', 'decisionMaking'), ('ndaPhysics', 'ndaPhysics'), ('ndaHistory', 'ndaHistory'), ('ndaChemistry', 'ndaChemistry'), ('ndaMaths', 'ndaMaths'), ('cdsMaths', 'cdsMaths'), ('dataAnalysisAndInterpretation', 'dataAnalysisAndInterpretation'), ('financialAwareness', 'financialAwareness'), ('financeAndAccounts', 'financeAndAccounts'), ('statistics', 'statistics')], default='mathsAdv', max_length=100000),
        ),
        migrations.CreateModel(
            name='DailyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('questions', models.ManyToManyField(blank=True, to='Questions.Questions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
