# Generated by Django 3.2.6 on 2021-09-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0020_auto_20210918_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquestions',
            name='exam',
            field=models.ManyToManyField(blank=True, to='Questions.Exams'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(choices=[('physicsAdv', 'physicsAdv'), ('mathsAdv', 'mathsAdv'), ('chemAdv', 'chemAdv'), ('physicsMains', 'physicsMains'), ('mathsMains', 'mathsMains'), ('chemMains', 'chemMains'), ('bio', 'bio'), ('reasoningHard', 'reasoningHard'), ('reasoningEasy', 'reasoningEasy'), ('currentAffairsWorld', 'currentAffairsWorld'), ('currentAffairsIndiaEasy', 'currentAffairsIndiaEasy'), ('currentAffairsIndiaHard', 'currentAffairsIndiaHard'), ('quantAptHard', 'quantAptHard'), ('quantAptEasy', 'quantAptEasy'), ('englishLangAndComprehension', 'englishLangAndComprehension'), ('basicComputer', 'basicComputer'), ('economyAndBanking', 'economyAndBanking'), ('geographyIndHard', 'geographyIndHard'), ('geographyIndEasy', 'geographyIndEasy'), ('geographyWorld', 'geographyWorld'), ('polityIndEasy', 'polityIndEasy'), ('polityIndHard', 'polityIndHard'), ('economyIndGen', 'economyIndGen'), ('economyIndBudgetAndSchemes', 'economyIndBudgetAndSchemes'), ('environmentAndEcologyEasy', 'environmentAndEcologyEasy'), ('environmentAndEcologyHard', 'environmentAndEcologyHard'), ('historyIndEasy', 'historyIndEasy'), ('historyIndHard', 'historyIndHard'), ('historyWorld', 'historyWorld'), ('InternationalRelationAndSecurity', 'InternationalRelationAndSecurity'), ('sciAndTechEasy', 'sciAndTechEasy'), ('sciAndTechHard', 'sciAndTechHard'), ('generalScience', 'generalScience'), ('geographyRajEasy', 'geographyRajEasy'), ('geographyRajHard', 'geographyRajHard'), ('historyRajEasy', 'historyRajEasy'), ('historyRajHard', 'historyRajHard'), ('artAndCultureRaj', 'artAndCultureRaj'), ('polityRajHard', 'polityRajHard'), ('polityRajEasy', 'polityRajEasy'), ('currentAffairsRajHard', 'currentAffairsRajHard'), ('currentAffairsRajEasy', 'currentAffairsRajEasy'), ('artAndCultureInd', 'artAndCultureInd'), ('economyRajHard', 'economyRajHard'), ('economyRajEasy', 'economyRajEasy'), ('constitutionAndGovernance', 'constitutionAndGovernance'), ('decisionMaking', 'decisionMaking'), ('ndaPhysics', 'ndaPhysics'), ('ndaHistory', 'ndaHistory'), ('ndaChemistry', 'ndaChemistry'), ('ndaMaths', 'ndaMaths'), ('cdsMaths', 'cdsMaths'), ('currentEvents', 'currentEvents'), ('dataAnalysisAndInterpretation', 'dataAnalysisAndInterpretation'), ('financialAwareness', 'financialAwareness'), ('financeAndAccounts', 'financeAndAccounts'), ('statistics', 'statistics')], default='mathsAdv', max_length=100000),
        ),
    ]
