# Generated by Django 3.2.6 on 2021-09-28 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Questions', '0023_auto_20210927_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquestions',
            name='updateTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PrevDailyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('questions', models.ManyToManyField(blank=True, related_name='prevDailyQuestions', to='Questions.Questions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
