# Generated by Django 3.2.9 on 2021-11-08 05:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0025_auto_20211016_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicequestions',
            name='unansweredQuesions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
    ]
