iasSubjects = ["currentAffairsWorld", 
                   "currentAffairsIndiaEasy", 
                   "currentAffairsIndiaHard", 
                   "geographyIndEasy", 
                   "geographyIndHard", 
                   "geographyWorld",
                   "polityIndEasy", 
                   "polityIndHard", 
                   "economyIndGen", 
                   "economyIndBudgetAndSchemes", 
                   "environmentAndEcologyHard", 
                   "environmentAndEcologyEasy", 
                   "historyIndEasy",
                   "historyIndHard",
                   "historyWorld",
                   "InternationalRelationAndSecurity", 
                   "sciAndTechHard", 
                   "artAndCultureInd", 
                   "constitutionAndGovernance",
                   "decisionMaking"]
    
jeeSubjects = ["physicsAdv", "mathsAdv", "chemAdv", "physicsMains", "mathsMains", "chemMains"]
jeeAdvSubjects = ["physicsAdv", "mathsAdv", "chemAdv"]
jeeMainsSubjects = ["physicsMains", "mathsMains", "chemMains"]

neetSubjects = ["physicsMains", "bio", "chemMains"]

rasSubjects = ["currentAffairsIndiaEasy", 
                "currentAffairsIndiaHard", 
                "geographyIndEasy", 
                "geographyWorld",
                "polityIndEasy",
                "geographyIndHard", 
                "polityIndHard", 
                "economyIndGen", 
                "economyIndBudgetAndSchemes",
                "environmentAndEcologyHard", 
                "environmentAndEcologyEasy", 
                "historyIndEasy",
                "historyIndHard",
                "sciAndTechEasy", 
                "sciAndTechHard", 
                "artAndCultureInd", 
                "constitutionAndGovernance",
                "geographyRajEasy", 
                "geographyRajHard", 
                "historyRajHard", 
                "historyRajEasy", 
                "artAndCultureRaj", 
                "polityRajEasy", 
                "polityRajHard", 
                "currentAffairsRajHard",
                "currentAffairsRajEasy", 
                "artAndCultureInd", 
                "economyRajHard",
                "economyRajEasy",
                "reasoningHard", 
                "reasoningEasy"]

ndaSubjects = ["ndaPhysics", 
                "ndaHistory", 
                "ndaChemistry", 
                "ndaMaths", 
                "currentEvents"]

cdsSubjects = ["reasoningEasy", 
                "reasoningHard", 
                "currentAffairsIndiaEasy", 
                "englishLangAndComprehension",
                "geographyIndEasy", 
                "polityIndEasy", 
                "historyIndEasy", 
                "sciAndTechEasy", 
                "cdsMaths", 
                "environmentAndEcologyEasy"]

ibpsPOSubjects = ["englishLangAndComprehension", 
                    "quantAptHard", 
                    "reasoningHard", 
                    "reasoningEasy", 
                    "economyAndBanking",
                    "dataAnalysisAndInterpretation", 
                    "financialAwareness",
                    "basicComputer",
                    "financeAndAccounts"]

ibpsClerkSubjects = ["englishLangAndComprehension", 
                        "quantAptEasy", 
                        "quantAptHard",
                        "reasoningEasy", 
                        "financialAwareness",
                        "basicComputer",
                        "financeAndAccounts"]

sscCGLSubjects = ["reasoningHard", 
                    "reasoningEasy", 
                    "historyIndEasy", 
                    "currentAffairsIndiaEasy", 
                    "geographyIndEasy",
                    "polityIndEasy",
                    "quantAptEasy",
                    "englishLangAndComprehension",
                    "financeAndAccounts",
                    "statistics"]

sscCHSLSubjects = ["reasoningHard", 
                    "reasoningEasy", 
                    "historyIndEasy", 
                    "currentAffairsIndiaEasy", 
                    "geographyIndEasy",
                    "polityIndEasy",
                    "quantAptEasy",
                    "englishLangAndComprehension"]

ntpcSubjects = ["reasoningHard", 
        "reasoningEasy", 
        "historyIndEasy", 
        "currentAffairsIndiaEasy", 
        "geographyIndEasy",
        "polityIndEasy",
        "quantAptEasy",
        "englishLangAndComprehension"]
