# Generated by Django 3.2.6 on 2021-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_chat_forum_forummessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forummessage',
            name='forum',
        ),
        migrations.AddField(
            model_name='forum',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='forumMessages', to='Chat.ForumMessage'),
        ),
    ]
