iasSubjects = ["currentAffairsWorldHard", 
                   "currentAffairsIndiaEasy", 
                   "currentAffairsIndiaHard", 
                   "geographyIndEasy", 
                   "geographyIndHard", 
                   "geographyWorld",
                   "polityIndEasy", 
                   "polityIndHard", 
                   "economyIndGen", 
                   "economyIndBudgetAndSchemes", 
                   "environmentAndEcologyHard", 
                   "environmentAndEcologyEasy", 
                   "historyIndEasy",
                   "historyIndHard",
                   "historyWorld",
                   "InternationalRelationAndSecurity", 
                   "sciAndTechHard", 
                   "artAndCultureInd", 
                   "constitutionAndGovernance",
                   "decisionMaking",
                   "iasMisc"]

iasHindiSubjects = ["currentAffairsWorldHardHindi", 
                   "currentAffairsIndiaEasyHindi", 
                   "currentAffairsIndiaHardHindi", 
                   "geographyIndEasyHindi", 
                   "geographyIndHardHindi", 
                   "geographyWorldHindi",
                   "polityIndEasyHindi", 
                   "polityIndHardHindi", 
                   "economyIndGenHindi", 
                   "economyIndBudgetAndSchemesHindi", 
                   "environmentAndEcologyHardHindi", 
                   "environmentAndEcologyEasyHindi", 
                   "historyIndEasyHindi",
                   "historyIndHardHindi",
                   "historyWorldHindi",
                   "InternationalRelationAndSecurityHindi", 
                   "sciAndTechHardHindi", 
                   "artAndCultureIndHindi", 
                   "constitutionAndGovernanceHindi",
                   "decisionMakingHindi",
                   "iasMiscHindi"]
    
jeeSubjects = ["physicsAdv", "mathsAdv", "chemAdv", "physicsMains", "mathsMains", "chemMains", "jeeMisc"]
jeeAdvSubjects = ["physicsAdv", "mathsAdv", "chemAdv", "jeeAdvMisc"]
jeeMainsSubjects = ["physicsMains", "mathsMains", "chemMains", "jeeMainsMisc"]

neetSubjects = ["physicsMains", "bio", "chemMains", "neetMisc", "physicsNeet", "chemNeet"]

rasSubjects = ["currentAffairsIndiaEasy", 
                "currentAffairsIndiaHard", 
                "currentAffairsWorldEasy", 
                "geographyIndEasy", 
                "geographyWorld",
                "polityIndEasy",
                "geographyIndHard", 
                "polityIndHard", 
                "economyIndGen", 
                "economyIndBudgetAndSchemes",
                "environmentAndEcologyHard", 
                "environmentAndEcologyEasy", 
                "historyIndEasy",
                "historyIndHard",
                "sciAndTechEasy", 
                "sciAndTechHard", 
                "artAndCultureInd", 
                "constitutionAndGovernance",
                "geographyRajEasy", 
                "geographyRajHard", 
                "historyRajHard", 
                "historyRajEasy", 
                "artAndCultureRaj", 
                "polityRajEasy", 
                "polityRajHard", 
                "currentAffairsRajHard",
                "currentAffairsRajEasy", 
                "economyRajHard",
                "economyRajEasy",
                "reasoningHard", 
                "reasoningEasy",
                "rasMisc",
                "iasMisc"]

rasHindiSubjects = [
        "currentAffairsIndiaEasyHindi", 
                "currentAffairsIndiaHardHindi", 
                "currentAffairsWorldEasyHindi", 
                "geographyIndEasyHindi", 
                "geographyWorldHindi",
                "polityIndEasyHindi",
                "geographyIndHardHindi", 
                "polityIndHardHindi", 
                "economyIndGenHindi", 
                "economyIndBudgetAndSchemesHindi",
                "environmentAndEcologyHardHindi", 
                "environmentAndEcologyEasyHindi", 
                "historyIndEasyHindi",
                "historyIndHardHindi",
                "sciAndTechEasyHindi", 
                "sciAndTechHardHindi", 
                "constitutionAndGovernanceHindi",
                "geographyRajEasyHindi", 
                "geographyRajHardHindi", 
                "historyRajHardHindi", 
                "historyRajEasyHindi", 
                "artAndCultureRajHindi", 
                "polityRajEasyHindi", 
                "polityRajHardHindi", 
                "currentAffairsRajHardHindi",
                "currentAffairsRajEasyHindi", 
                "artAndCultureIndHindi", 
                "economyRajHardHindi",
                "economyRajEasyHindi",
                "reasoningHardHindi", 
                "reasoningEasyHindi",
                "rasMiscHindi", 
                "quantAptEasyHindi", 
                "iasMiscHindi"]

ndaSubjects = ["physicsNeet", 
                "ndaHistory", 
                "chemNeet", 
                "ndaMaths", 
                "currentEvents",
                "mathsMains",
                "ndaMisc"]

cdsSubjects = ["reasoningEasy", 
                "reasoningHard", 
                "currentAffairsIndiaEasy", 
                "englishLangAndComprehensionHard",
                "englishLangAndComprehensionEasy",
                "geographyIndEasy", 
                "polityIndEasy", 
                "historyIndEasy", 
                "sciAndTechEasy", 
                "mathsMains", 
                "cdsMaths",
                "environmentAndEcologyEasy",
                "cdsMisc"]

ibpsPOSubjects = ["englishLangAndComprehensionHard", 
                    "quantAptHard", 
                    "reasoningHard", 
                    "reasoningEasy", 
                    "economyAndBanking",
                    "dataAnalysisAndInterpretation", 
                    "financialAwareness",
                    "basicComputer",
                    "financeAndAccounts",
                    "ibpsPOSSCMisc"]

ibpsClerkSubjects = ["englishLangAndComprehensionEasy",
                        "englishLangAndComprehensionHard", 
                        "quantAptEasyHindi", 
                        "quantAptHardHindi",
                        "reasoningEasyHindi", 
                        "financialAwareness",
                        "basicComputer",
                        "financeAndAccounts",
                        "ibpsClerkSSCMisc"]

sscCGLSubjects = ["reasoningHard", 
                    "reasoningEasy", 
                    "historyIndEasy", 
                    "currentAffairsIndiaEasy", 
                    "geographyIndEasy",
                    "polityIndEasy",
                    "quantAptEasy",
                    "quantAptHard",
                    "englishLangAndComprehensionHard",
                    "englishLangAndComprehensionEasy",
                    "financeAndAccounts",
                    "statistics",
                    "ibpsPOSSCMisc"]

sscCGLHindiSubjects = ["reasoningHardHindi", 
                    "reasoningEasyHindi", 
                    "historyIndEasyHindi", 
                    "currentAffairsIndiaEasyHindi", 
                    "geographyIndEasyHindi",
                    "polityIndEasyHindi",
                    "quantAptEasyHindi",
                    "quantAptHardHindi",
                    "englishLangAndComprehensionHard",
                    "englishLangAndComprehensionEasy",
                    "financeAndAccounts",
                    "statisticsHindi",
                    "sscCGLMiscHindi"]

sscCHSLSubjects = [
                "reasoningHardHindi", 
                    "reasoningEasyHindi", 
                    "historyIndEasyHindi", 
                    "currentAffairsIndiaEasyHindi", 
                    "geographyIndEasyHindi",
                    "polityIndEasyHindi",
                    "quantAptEasyHindi",
                    "quantAptHardHindi",
                    "englishLangAndComprehensionHard",
                    "englishLangAndComprehensionEasy",
                    "ibpsClerkSSCMisc"
                    ]

ntpcSubjects = [
                    "reasoningHardHindi", 
                    "reasoningEasyHindi", 
                    "historyIndEasyHindi", 
                    "currentAffairsIndiaEasyHindi", 
                    "geographyIndEasyHindi",
                    "polityIndEasyHindi",
                    "quantAptEasyHindi",
                    "quantAptHardHindi",
                    "englishLangAndComprehensionHard",
                    "englishLangAndComprehensionEasy",
                    "financeAndAccounts",
                    "ibpsClerkSSCMisc"]



reet1Subjects = [
        "reet1Misc",
        "childDevelopmentAndEdu",
        "hindi",
        "englishLangAndComprehensionEasy",
        "quantAptEasyHindi",
        "generalScience"]

reet2Subjects = [
        "childDevelopmentAndEdu",
        "hindi",
        "englishLangAndComprehensionEasy",
        "staticGK",
        "geographyIndEasyHindi", 
        "geographyWorldHindi",
        "polityIndEasyHindi",
        "geographyIndHardHindi", 
        "polityIndHardHindi", 
        "economyIndGenHindi", 
        "historyIndEasyHindi",
        "historyIndHardHindi",
        "constitutionAndGovernanceHindi",
        "geographyRajHardHindi", 
        "historyRajHardHindi", 
        "artAndCultureRajHindi", 
        "polityRajHardHindi", 
        "currentAffairsRajHardHindi",
        "artAndCultureIndHindi", 
        "rasMiscHindi"]

reet2ScienceSubjects = [
        "quantAptEasyHindi",
        "quantAptHardHindi",
        "childDevelopmentAndEdu",
        "hindi",
        "englishLangAndComprehensionEasy",
        "bioHindi",
        "physicsHindi", 
        "chemHindi",
        "grade2ndScienceMisc",
        "generalScience"
]



sipaper1Subjects = ["hindi"]

sipaper2Subjects = [
        "reasoningEasyHindi",
        "reasoningHardHindi",
        "quantAptEasyHindi",
        "currentAffairsIndiaEasyHindi",
        "currentAffairsRajEasyHindi",
        "currentAffairsWorldEasyHindi",
        "geographyIndEasyHindi",
        "polityIndEasyHindi",
        "economyIndGenHindi",
        "historyIndEasyHindi",
        "generalScience",
        "geographyRajEasyHindi",
        "geographyRajHardHindi",
        "historyRajEasyHindi",
        "historyRajHard",
        "artAndCultureRajHindi",
        "economyRajHardHindi",
        "economyRajEasyHindi",
        "patwariMisc"
]

patwariSubjects = [
        "reasoningEasyHindi",
        "reasoningHardHindi",
        "quantAptEasyHindi",
        "currentAffairsIndiaEasyHindi",
        "currentAffairsRajEasyHindi",
        "currentAffairsWorldEasyHindi",
        "geographyIndEasyHindi",
        "polityIndEasyHindi",
        "economyIndGenHindi",
        "historyIndEasyHindi",
        "generalScience",
        "geographyRajEasyHindi",
        "geographyRajHardHindi",
        "historyRajEasyHindi",
        "historyRajHard",
        "artAndCultureRajHindi",
        "economyRajHardHindi",
        "economyRajEasyHindi",
        "hindi",
        "currentAffairsRajHard",
        "englishLangAndComprehensionEasy",
        "basicComputer",
        "economyIndBudgetAndSchemes",
        "patwariMisc"
]

grade2ndSubjects = [
        "currentAffairsIndiaEasyHindi",
        "currentAffairsRajEasyHindi",
        "currentAffairsWorldEasyHindi",
        "geographyIndEasyHindi",
        "polityIndEasyHindi",
        "economyIndGenHindi",
        "historyIndEasyHindi",
        "generalScience",
        "geographyRajEasyHindi",
        "geographyRajHardHindi",
        "historyRajEasyHindi",
        "historyRajHard",
        "artAndCultureRajHindi",
        "economyRajHardHindi",
        "economyRajEasyHindi",
        "hindi",
        "currentAffairsRajHard",
        "englishLangAndComprehensionEasy",
        "basicComputer",
        "economyIndBudgetAndSchemes",
        "teachingApt",
        "rasMiscHindi",
        "patwariMisc"
]

grade2ndScienceSubjects = ["bioHindi", "grade2ndScienceMisc", "physicsHindi", "chemHindi"]

grade2ndSSSubjects = [
        "childDevelopmentAndEdu",
        "hindi",
        "englishLangAndComprehensionEasy",
        "staticGK",
        "geographyIndEasyHindi", 
        "geographyWorldHindi",
        "polityIndEasyHindi",
        "geographyIndHardHindi", 
        "polityIndHardHindi", 
        "economyIndGenHindi", 
        "historyIndEasyHindi",
        "historyIndHardHindi",
        "constitutionAndGovernanceHindi",
        "geographyRajHardHindi", 
        "historyRajHardHindi", 
        "artAndCultureRajHindi", 
        "polityRajHardHindi", 
        "currentAffairsRajHardHindi",
        "artAndCultureIndHindi", 
        "rasMiscHindi",
        "patwariMisc"
]


rajLDCSubjects = [
        "reasoningEasyHindi",
        "reasoningHardHindi",
        "quantAptEasyHindi",
        "currentAffairsIndiaEasyHindi",
        "currentAffairsRajEasyHindi",
        "currentAffairsWorldEasyHindi",
        "geographyIndEasyHindi",
        "polityIndEasyHindi",
        "economyIndGenHindi",
        "historyIndEasyHindi",
        "generalScience",
        "geographyRajEasyHindi",
        "geographyRajHardHindi",
        "historyRajEasyHindi",
        "historyRajHard",
        "artAndCultureRajHindi",
        "economyRajHardHindi",
        "economyRajEasyHindi",
        "hindi",
        "currentAffairsRajHard",
        "englishLangAndComprehensionEasy",
        "basicComputer",
        "economyIndBudgetAndSchemes",
        "patwariMisc"
]



sscGDSubjects = [
        "staticGK",
        "sscMTSGK",
        "hindi",
        "sscMTSReasoning",
        "gdQuantApt",
        "sscMTSMisc"
]

sscMTSSubjects = [
        "staticGK",
        "gdQuantApt",
        "sscMTSGK",
        "sscMTSReasoning",
        "englishLangAndComprehensionEasy",
        "sscMTSMisc"
]

rajPoliceConstSubjects = [
        "staticGK",
        "sscMTSGK",
        "sscMTSReasoning",
        "rpcGKRaj",
        "basicComputer",
        "sscMTSMisc"
]

rrbGDSubjects = [
        "staticGK",
        "gdQuantApt",
        "sscMTSGK",
        "sscMTSReasoning",
        "sscMTSMisc"
]



"""


Required Questions and Can be Found :
        1. basicComputer -> Hindi
        2. bioHindi
        3. staticGK -> Hindi
        4. generalScience -> Hindi
        5. rpcGKRaj
        6. sscMTSReasoning
        7. childDevelopmentAndEdu

Add new: 

        "quantAptHardHindi",
        "statisticsHindi",
        "currentAffairsWorldHardHindi",
        "currentAffairsIndiaEasyHindi", 
        "currentAffairsIndiaHardHindi", 
        "currentAffairsWorldEasyHindi", 
        "geographyIndEasyHindi", 
        "geographyWorldHindi",
        "polityIndEasyHindi",
        "geographyIndHardHindi", 
        "polityIndHardHindi", 
        "economyIndGenHindi", 
        "economyIndBudgetAndSchemesHindi",
        "environmentAndEcologyHardHindi", 
        "environmentAndEcologyEasyHindi", 
        "historyIndEasyHindi",
        "historyIndHardHindi",
        "historyWorldHindi",
        "sciAndTechEasyHindi", 
        "sciAndTechHardHindi", 
        "constitutionAndGovernanceHindi",
        "InternationalRelationAndSecurityHindi",
        "geographyRajEasyHindi", 
        "geographyRajHardHindi", 
        "historyRajHardHindi", 
        "historyRajEasyHindi", 
        "artAndCultureRajHindi", 
        "polityRajEasyHindi", 
        "polityRajHardHindi", 
        "currentAffairsRajHardHindi",
        "currentAffairsRajEasyHindi", 
        "artAndCultureIndHindi", 
        "economyRajHardHindi",
        "economyRajEasyHindi",
        "reasoningHardHindi", 
        "reasoningEasyHindi",
        "decisionMakingHindi", 
        "physicsNeetHindi", 
        "chemNeetHindi",
        "ibpsClerkSSCMisc",



Changes : 

"""




subjects_updated = [('physicsAdv', 'physicsAdv'),
        ('mathsAdv', 'mathsAdv'),
        ('chemAdv', 'chemAdv'),
        ('physicsMains', 'physicsMains'),
        ('mathsMains', 'mathsMains'),
        ('chemMains', 'chemMains'),
        ('physicsNeet', 'physicsNeet'),
        ('chemNeet', 'chemNeet'),
        ('bio', 'bio'),
        ('reasoningHard', 'reasoningHard'),
        ('reasoningEasy', 'reasoningEasy'),
        ('currentAffairsWorldEasy', 'currentAffairsWorldEasy'),
        ('currentAffairsWorldHard', 'currentAffairsWorldHard'),
        ('currentAffairsIndiaEasy', 'currentAffairsIndiaEasy'),
        ('currentAffairsIndiaHard', 'currentAffairsIndiaHard'),
        ('quantAptHard', 'quantAptHard'),
        ('quantAptEasy', 'quantAptEasy'),
        ('quantAptEasyHindi', 'quantAptEasyHindi'),
        ('englishLangAndComprehensionEasy', 'englishLangAndComprehensionEasy'),
        ('englishLangAndComprehensionHard', 'englishLangAndComprehensionHard'),
        ('basicComputer', 'basicComputer'),
        ('economyAndBanking', 'economyAndBanking'),
        ('geographyIndHard', 'geographyIndHard'),
        ('geographyIndEasy', 'geographyIndEasy'),
        ('geographyWorld', 'geographyWorld'),
        ('polityIndEasy', 'polityIndEasy'),
        ('polityIndHard', 'polityIndHard'),
        ('economyIndGen', 'economyIndGen'),
        ('economyIndBudgetAndSchemes', 'economyIndBudgetAndSchemes'),
        ('environmentAndEcologyEasy', 'environmentAndEcologyEasy'),
        ('environmentAndEcologyHard', 'environmentAndEcologyHard'),
        ('historyIndEasy', 'historyIndEasy'),
        ('historyIndHard', 'historyIndHard'),
        ('historyWorld', 'historyWorld'),
        ('InternationalRelationAndSecurity', 'InternationalRelationAndSecurity'),
        ('sciAndTechEasy', 'sciAndTechEasy'),
        ('sciAndTechHard', 'sciAndTechHard'),
        ('generalScience', 'generalScience'),
        ('geographyRajEasy', 'geographyRajEasy'),
        ('geographyRajHard', 'geographyRajHard'),
        ('historyRajEasy', 'historyRajEasy'),
        ('historyRajHard', 'historyRajHard'),
        ('artAndCultureRaj', 'artAndCultureRaj'),
        ('polityRajHard', 'polityRajHard'),
        ('polityRajEasy', 'polityRajEasy'),
        ('currentAffairsRajHard', 'currentAffairsRajHard'),
        ('currentAffairsRajEasy', 'currentAffairsRajEasy'),
        ('artAndCultureInd', 'artAndCultureInd'),
        ('economyRajHard', 'economyRajHard'),
        ('economyRajEasy', 'economyRajEasy'),
        ('constitutionAndGovernance', 'constitutionAndGovernance'),
        ('decisionMaking', 'decisionMaking'),
        ('ndaHistory', 'ndaHistory'),
        ('ndaMaths', 'ndaMaths'),
        ('cdsMaths', 'cdsMaths'),
        ('currentEvents', 'currentEvents'),
        ('dataAnalysisAndInterpretation', 'dataAnalysisAndInterpretation'),
        ('financialAwareness', 'financialAwareness'),
        ('financeAndAccounts', 'financeAndAccounts'),
        ('statistics', 'statistics'),
        ('childDevelopmentAndEdu', 'childDevelopmentAndEdu'),
        ('teachingApt', 'teachingApt'),
        ('hindi', 'hindi'),
        ('staticGK', 'staticGK'),
        ('sscMTSGK', 'sscMTSGK'),
        ('rpcGKRaj', 'rpcGKRaj'),
        ('sscMTSReasoning', 'sscMTSReasoning'),
        ('gdQuantApt', 'gdQuantApt'),
        ('iasMisc', 'iasMisc'),
        ('jeeMisc', 'jeeMisc'),
        ('jeeMainsMisc', 'jeeMainsMisc'),
        ('jeeAdvMisc', 'jeeAdvMisc'),
        ('neetMisc', 'neetMisc'),
        ('rasMisc', 'rasMisc'),
        ('ibpsPOSSCMisc', 'ibpsPOSSCMisc'),
        ('ndaMisc', 'ndaMisc'),
        ('cdsMisc', 'cdsMisc'),
        ('reet1Misc', 'reet1Misc'),
        ('patwariMisc', 'patwariMisc'),
        ('grade2ndScienceMisc', 'grade2ndScienceMisc'),
        ('sscMTSMisc', 'sscMTSMisc'),
        ('iasMiscHindi', 'iasMiscHindi'),
        ('rasMiscHindi', 'rasMiscHindi'),
        ('sscCGLMiscHindi', 'sscCGLMiscHindi'),
        ('currentAffairsWorldHardHindi', 'currentAffairsWorldHardHindi'),
        ('currentAffairsIndiaEasyHindi', 'currentAffairsIndiaEasyHindi'),
        ('currentAffairsIndiaHardHindi', 'currentAffairsIndiaHardHindi'),
        ('geographyIndEasyHindi', 'geographyIndEasyHindi'),
        ('geographyIndHardHindi', 'geographyIndHardHindi'),
        ('geographyWorldHindi', 'geographyWorldHindi'),
        ('polityIndEasyHindi', 'polityIndEasyHindi'),
        ('polityIndHardHindi', 'polityIndHardHindi'),
        ('economyIndGenHindi', 'economyIndGenHindi'),
        ('economyIndBudgetAndSchemesHindi', 'economyIndBudgetAndSchemesHindi'),
        ('environmentAndEcologyHardHindi', 'environmentAndEcologyHardHindi'),
        ('environmentAndEcologyEasyHindi', 'environmentAndEcologyEasyHindi'),
        ('historyIndEasyHindi', 'historyIndEasyHindi'),
        ('historyIndHardHindi', 'historyIndHardHindi'),
        ('historyWorldHindi', 'historyWorldHindi'),
        ('InternationalRelationAndSecurityHindi',
        'InternationalRelationAndSecurityHindi'),
        ('sciAndTechHardHindi', 'sciAndTechHardHindi'),
        ('artAndCultureIndHindi', 'artAndCultureIndHindi'),
        ('constitutionAndGovernanceHindi', 'constitutionAndGovernanceHindi'),
        ('decisionMakingHindi', 'decisionMakingHindi'),
        ('currentAffairsWorldEasyHindi', 'currentAffairsWorldEasyHindi'),
        ('sciAndTechEasyHindi', 'sciAndTechEasyHindi'),
        ('geographyRajEasyHindi', 'geographyRajEasyHindi'),
        ('geographyRajHardHindi', 'geographyRajHardHindi'),
        ('historyRajHardHindi', 'historyRajHardHindi'),
        ('historyRajEasyHindi', 'historyRajEasyHindi'),
        ('artAndCultureRajHindi', 'artAndCultureRajHindi'),
        ('polityRajEasyHindi', 'polityRajEasyHindi'),
        ('polityRajHardHindi', 'polityRajHardHindi'),
        ('currentAffairsRajHardHindi', 'currentAffairsRajHardHindi'),
        ('currentAffairsRajEasyHindi', 'currentAffairsRajEasyHindi'),
        ('economyRajHardHindi', 'economyRajHardHindi'),
        ('economyRajEasyHindi', 'economyRajEasyHindi'),
        ('reasoningHardHindi', 'reasoningHardHindi'),
        ('reasoningEasyHindi', 'reasoningEasyHindi'),
        ('quantAptHardHindi', 'quantAptHardHindi'),
        ('ibpsClerkSSCMisc', 'ibpsClerkSSCMisc'),
        ('statisticsHindi', 'statisticsHindi'),
        ('bioHindi', 'bioHindi'),
        ('physicsHindi', 'physicsHindi'),
        ('chemHindi', 'chemHindi'),
        ('generalScience', 'generalScience')]







[("physicsAdv", "physicsAdv"), 
            ("mathsAdv","mathsAdv"),
            ("chemAdv","chemAdv"),
            ("physicsMains","physicsMains"), 
            ("mathsMains", "mathsMains"),
            ("chemMains","chemMains"),
            ("physicsNeet", "physicsNeet"),
            ("chemNeet", "chemNeet"),
            ("bio", "bio"),
            ("reasoningHard", "reasoningHard"),
            ("reasoningEasy","reasoningEasy"),
            ("currentAffairsWorldEasy", "currentAffairsWorldEasy"),
            ("currentAffairsWorldHard", "currentAffairsWorldHard"),
            ("currentAffairsIndiaEasy", "currentAffairsIndiaEasy"),
            ("currentAffairsIndiaHard", "currentAffairsIndiaHard"),
            ("quantAptHard", "quantAptHard"),
            ("quantAptEasy", "quantAptEasy"),
            ("quantAptEasyHindi", "quantAptEasyHindi"),
            ("englishLangAndComprehensionEasy","englishLangAndComprehensionEasy"),
            ("englishLangAndComprehensionHard","englishLangAndComprehensionHard"),
            ("basicComputer", "basicComputer"),
            ("economyAndBanking", "economyAndBanking"), 
            ("geographyIndHard", "geographyIndHard"),
            ("geographyIndEasy", "geographyIndEasy"),
            ("geographyWorld","geographyWorld"),
            ("polityIndEasy", "polityIndEasy"),
            ("polityIndHard", "polityIndHard"),
            ("economyIndGen", "economyIndGen"),
            ("economyIndBudgetAndSchemes", "economyIndBudgetAndSchemes"),
            ("environmentAndEcologyEasy","environmentAndEcologyEasy"),
            ("environmentAndEcologyHard","environmentAndEcologyHard"),
            ("historyIndEasy", "historyIndEasy"),
            ("historyIndHard", "historyIndHard"),
            ("historyWorld", "historyWorld"),
            ("InternationalRelationAndSecurity", "InternationalRelationAndSecurity"),
            ("sciAndTechEasy","sciAndTechEasy"), 
            ("sciAndTechHard","sciAndTechHard"), 
            ("generalScience", "generalScience"), 
            ("geographyRajEasy", "geographyRajEasy"),
            ("geographyRajHard", "geographyRajHard"),
            ("historyRajEasy", "historyRajEasy"), 
            ("historyRajHard", "historyRajHard"), 
            ("artAndCultureRaj", "artAndCultureRaj"), 
            ("polityRajHard", "polityRajHard"),
            ("polityRajEasy", "polityRajEasy"),
            ("currentAffairsRajHard", "currentAffairsRajHard"), 
            ("currentAffairsRajEasy", "currentAffairsRajEasy"),
            ("artAndCultureInd", "artAndCultureInd"), 
            ("economyRajHard", "economyRajHard"), 
            ("economyRajEasy", "economyRajEasy"), 
            ("constitutionAndGovernance", "constitutionAndGovernance"), 
            ("decisionMaking","decisionMaking"),
            ("ndaHistory", "ndaHistory"),
            ("ndaMaths","ndaMaths"),
            ("cdsMaths","cdsMaths"),
            ("currentEvents", "currentEvents"),
            ("dataAnalysisAndInterpretation", "dataAnalysisAndInterpretation"),
            ("financialAwareness", "financialAwareness"),
            ("financeAndAccounts", "financeAndAccounts"),
            ("statistics","statistics"),
            ("childDevelopmentAndEdu", "childDevelopmentAndEdu"),
            ("teachingApt", "teachingApt"),
            ("hindi", "hindi"),
            ("staticGK", "staticGK"),
            ("sscMTSGK", "sscMTSGK"),
            ("rpcGKRaj", "rpcGKRaj"),
            ("sscMTSReasoning", "sscMTSReasoning"),
            ('gdQuantApt', "gdQuantApt"),
            ("iasMisc", "iasMisc"),
            ("jeeMisc", "jeeMisc"),
            ("jeeMainsMisc", "jeeMainsMisc"),
            ("jeeAdvMisc", "jeeAdvMisc"),
            ("neetMisc", "neetMisc"),
            ("rasMisc", "rasMisc"),
            ("ibpsPOSSCMisc", "ibpsPOSSCMisc"),
            ("ndaMisc", "ndaMisc"),
            ("cdsMisc", "cdsMisc"),
            ("reet1Misc", "reet1Misc"),
            ("patwariMisc", "patwariMisc"),
            ("grade2ndScienceMisc", "grade2ndScienceMisc"),
            ("sscMTSMisc", "sscMTSMisc"),
            ("iasMiscHindi", "iasMiscHindi"),
            ("rasMiscHindi", "rasMiscHindi"),
            ("sscCGLMiscHindi", "sscCGLMiscHindi")
    ]