# Generated by Django 3.2.6 on 2021-09-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isFree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isMaxPremium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isMinPremium',
            field=models.BooleanField(default=False),
        ),
    ]
