# Generated by Django 3.2.9 on 2021-12-31 22:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_addedquestiondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='premiumExams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
