# Generated by Django 3.2.6 on 2021-09-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210905_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isFree',
            field=models.BooleanField(default=True),
        ),
    ]
