# Generated by Django 3.2.6 on 2021-09-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_isfree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isMaxPremium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isMinPremium',
        ),
        migrations.AddField(
            model_name='user',
            name='premium100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='premium30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='premium300',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='premium50',
            field=models.BooleanField(default=False),
        ),
    ]
