# Generated by Django 3.2.6 on 2021-09-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210911_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isFree',
        ),
        migrations.RemoveField(
            model_name='user',
            name='premium100',
        ),
        migrations.RemoveField(
            model_name='user',
            name='premium30',
        ),
        migrations.RemoveField(
            model_name='user',
            name='premium300',
        ),
        migrations.RemoveField(
            model_name='user',
            name='premium50',
        ),
        migrations.AddField(
            model_name='user',
            name='cancelAtPeriodEnd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='stripeId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripeSubscriptionId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
