# Generated by Django 3.2.6 on 2021-09-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210911_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership',
        ),
        migrations.AddField(
            model_name='user',
            name='isFree',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membershipOf100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='membershipOf30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='membershipOf50',
            field=models.BooleanField(default=False),
        ),
    ]
