# Generated by Django 3.2.6 on 2021-09-19 10:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210915_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premiumExams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=None),
        ),
    ]
