# Generated by Django 3.2.6 on 2021-09-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_user_premiumexams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
