# Generated by Django 3.2.6 on 2021-09-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20210921_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cancelAtPeriodEnd',
        ),
        migrations.AddField(
            model_name='user',
            name='mebershipEndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
